# This workflow determine which processor have changed,
# builds and pushes a Singularity container for each of those processor plugins

name: commit_docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "commit_documentation"
  commit_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps in the workflow
    
    steps:
      - name: Track Changes
        id: track-changes
        uses:  AceFire6/file_changes@v0.1.0
        with:
          change-map: |
            rst: {"globs": "*.rst", "separateDeleted": true}
      - name: Commit Files
        run: echo "Changes: ${{ steps.track-changes.rst}}"
