# This workflow determine which processor have changed,
# builds and pushes a Singularity container for each of those processor plugins

name: commit_docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "commit_documentation"
  commit_documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps in the workflow
    
    steps:
      # Get all changed files first
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v31
        
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          
      # Getting all rst files
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v31
        with:
          files: |
            *.rst
            
      #Testing the rst file retrieval      
      - name: Run step if any of the listed files above change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
